# Generated by Django 6.0.2 on 2026-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StravaActivity",
            fields=[
                ("activity_id", models.IntegerField(primary_key=True, serialize=False)),
                ("activity_name", models.CharField(max_length=255)),
                ("activity_description", models.TextField()),
                ("activity_type", models.CharField(max_length=255)),
            ],
        ),
    ]
