# Generated by Django 6.0.2 on 2026-02-25 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stravaactivity",
            name="activity_description",
        ),
        migrations.AddField(
            model_name="stravaactivity",
            name="distance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="stravaactivity",
            name="elapsed_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stravaactivity",
            name="moving_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stravaactivity",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stravaactivity",
            name="total_elevation_gain",
            field=models.FloatField(default=0),
        ),
    ]
