# Generated by Django 6.0.2 on 2026-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strava_api", "0002_remove_stravaactivity_activity_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stravaactivity",
            name="activity_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
