# Generated by Django 6.0.2 on 2026-02-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dbtest",
            fields=[
                ("activity_id", models.IntegerField(primary_key=True, serialize=False)),
                ("activity_name", models.CharField(max_length=255)),
                ("activity_type", models.CharField(max_length=255)),
                ("distance", models.FloatField(default=0)),
                ("moving_time", models.IntegerField(default=0)),
                ("elapsed_time", models.IntegerField(default=0)),
                ("total_elevation_gain", models.FloatField(default=0)),
            ],
        ),
    ]
